In [1]:
import adaboost
import numpy as np

In [2]:
datMat,classLabels=adaboost.loadSimpData()

In [3]:
datMat

matrix([[1. , 2.1],
        [2. , 1.1],
        [1.3, 1. ],
        [1. , 1. ],
        [2. , 1. ]])

In [4]:
classLabels

[1.0, 1.0, -1.0, -1.0, 1.0]

In [5]:
D = np.ones(5)/5

In [6]:
adaboost.buildStump(datMat,classLabels,D)

({'feature': 0, 'value': 1.3, 'ineq': 'lt'},
 array([-1.,  1., -1., -1.,  1.]),
 0.2)

In [7]:
adaboost.adaBoostTrainDS(datMat,classLabels,9)

D= [0.2 0.2 0.2 0.2 0.2]
predict:  [-1.  1. -1. -1.  1.]
aggpredict= [-0.69314718  0.69314718 -0.69314718 -0.69314718  0.69314718]
total error:  0.2
D= [0.5   0.125 0.125 0.125 0.125]
predict:  [ 1.  1. -1. -1. -1.]
aggpredict= [ 0.27980789  1.66610226 -1.66610226 -1.66610226 -0.27980789]
total error:  0.2
D= [0.28571429 0.07142857 0.07142857 0.07142857 0.5       ]
predict:  [1. 1. 1. 1. 1.]
aggpredict= [ 1.17568763  2.56198199 -0.77022252 -0.77022252  0.61607184]
total error:  0.0


[{'feature': 0, 'value': 1.3, 'ineq': 'lt', 'alpha': 0.6931471805599453},
 {'feature': 1, 'value': 1.0, 'ineq': 'lt', 'alpha': 0.9729550745276565},
 {'feature': 0, 'value': 0.9, 'ineq': 'lt', 'alpha': 0.8958797346140273}]

In [8]:
datArr,labelArr = adaboost.loadSimpData()
classifierArr = adaboost.adaBoostTrainDS(datArr,labelArr,30)

D= [0.2 0.2 0.2 0.2 0.2]
predict:  [-1.  1. -1. -1.  1.]
aggpredict= [-0.69314718  0.69314718 -0.69314718 -0.69314718  0.69314718]
total error:  0.2
D= [0.5   0.125 0.125 0.125 0.125]
predict:  [ 1.  1. -1. -1. -1.]
aggpredict= [ 0.27980789  1.66610226 -1.66610226 -1.66610226 -0.27980789]
total error:  0.2
D= [0.28571429 0.07142857 0.07142857 0.07142857 0.5       ]
predict:  [1. 1. 1. 1. 1.]
aggpredict= [ 1.17568763  2.56198199 -0.77022252 -0.77022252  0.61607184]
total error:  0.0


In [9]:
adaboost.adaClassify([[0, 0]],classifierArr)   # 假设输入的是一组测试数据，所以第一个参数是个二维的数组

[-2.56198199]


array([-1.])

In [10]:
adaboost.adaClassify([[5, 5],[0,0]],classifierArr)

[ 2.56198199 -2.56198199]


array([ 1., -1.])