In [1]:
import adaboost
import numpy as np

In [2]:
datMat,classLabels=adaboost.loadSimpData()

In [3]:
datMat

matrix([[1. , 2.1],
        [2. , 1.1],
        [1.3, 1. ],
        [1. , 1. ],
        [2. , 1. ]])

In [4]:
classLabels

[1.0, 1.0, -1.0, -1.0, 1.0]

In [5]:
D = np.ones(5)/5

In [6]:
adaboost.buildStump(datMat,classLabels,D)

({'feature': 0, 'value': 1.3, 'ineq': 'lt'},
 array([-1.,  1., -1., -1.,  1.]),
 0.2)

In [7]:
adaboost.adaBoostTrainDS(datMat,classLabels,9)

D= [0.2 0.2 0.2 0.2 0.2]
predict:  [-1.  1. -1. -1.  1.]
aggpredict= [-0.69314718  0.69314718 -0.69314718 -0.69314718  0.69314718]
total error:  0.2
D= [0.5   0.125 0.125 0.125 0.125]
predict:  [ 1.  1. -1. -1. -1.]
aggpredict= [ 0.27980789  1.66610226 -1.66610226 -1.66610226 -0.27980789]
total error:  0.2
D= [0.28571429 0.07142857 0.07142857 0.07142857 0.5       ]
predict:  [1. 1. 1. 1. 1.]
aggpredict= [ 1.17568763  2.56198199 -0.77022252 -0.77022252  0.61607184]
total error:  0.0


[{'feature': 0, 'value': 1.3, 'ineq': 'lt', 'alpha': 0.6931471805599453},
 {'feature': 1, 'value': 1.0, 'ineq': 'lt', 'alpha': 0.9729550745276565},
 {'feature': 0, 'value': 0.9, 'ineq': 'lt', 'alpha': 0.8958797346140273}]

In [8]:
datArr,labelArr = adaboost.loadSimpData()
classifierArr = adaboost.adaBoostTrainDS(datArr,labelArr,30)

D= [0.2 0.2 0.2 0.2 0.2]
predict:  [-1.  1. -1. -1.  1.]
aggpredict= [-0.69314718  0.69314718 -0.69314718 -0.69314718  0.69314718]
total error:  0.2
D= [0.5   0.125 0.125 0.125 0.125]
predict:  [ 1.  1. -1. -1. -1.]
aggpredict= [ 0.27980789  1.66610226 -1.66610226 -1.66610226 -0.27980789]
total error:  0.2
D= [0.28571429 0.07142857 0.07142857 0.07142857 0.5       ]
predict:  [1. 1. 1. 1. 1.]
aggpredict= [ 1.17568763  2.56198199 -0.77022252 -0.77022252  0.61607184]
total error:  0.0


In [9]:
adaboost.adaClassify([[0, 0]],classifierArr)   # 假设输入的是一组测试数据，所以第一个参数是个二维的数组

[-2.56198199]


array([-1.])

In [10]:
adaboost.adaClassify([[5, 5],[0,0]],classifierArr)

[ 2.56198199 -2.56198199]


array([ 1., -1.])

In [11]:
datArr,labelArr = adaboost.loadDataSet('horseColicTraining2.txt')
classifierArray = adaboost.adaBoostTrainDS(datArr,labelArr,10)
testArr,testLabelArr = adaboost.loadDataSet('horseColicTest2.txt')
prediction10 = adaboost.adaClassify(testArr,classifierArray)

D= [0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448
 0.00334448 0.00334448 0.00334448 0.00334448 0.00334448 0.0

D= [0.00335068 0.00843582 0.00179355 0.00843582 0.00451553 0.00179355
 0.00179355 0.00843582 0.00335068 0.00451553 0.00179355 0.00179355
 0.00179355 0.00843582 0.00179355 0.00335068 0.00179355 0.00179355
 0.00179355 0.00335068 0.00451553 0.00179355 0.00179355 0.00179355
 0.00179355 0.00179355 0.00179355 0.00179355 0.00843582 0.00179355
 0.00179355 0.00843582 0.00179355 0.00179355 0.00451553 0.00179355
 0.00843582 0.00843582 0.00179355 0.00843582 0.00179355 0.00179355
 0.00179355 0.00335068 0.00179355 0.00179355 0.00843582 0.00179355
 0.00451553 0.00179355 0.00179355 0.00843582 0.00179355 0.00179355
 0.00451553 0.00843582 0.00179355 0.00335068 0.00179355 0.00179355
 0.00179355 0.00179355 0.00451553 0.00451553 0.00179355 0.00179355
 0.00335068 0.00179355 0.00335068 0.00179355 0.00843582 0.00179355
 0.00843582 0.00179355 0.00843582 0.00843582 0.00179355 0.00179355
 0.00335068 0.00335068 0.00335068 0.00179355 0.00179355 0.00179355
 0.00179355 0.00179355 0.00335068 0.00843582 0.00179355 0.0

D= [0.00261936 0.00659463 0.00140209 0.00659463 0.00352998 0.00140209
 0.00140209 0.00659463 0.00261936 0.00626457 0.00248826 0.00248826
 0.00140209 0.00659463 0.00248826 0.00261936 0.00140209 0.00140209
 0.00248826 0.00464853 0.00626457 0.00140209 0.00140209 0.00248826
 0.00248826 0.00248826 0.00248826 0.00140209 0.01170335 0.00140209
 0.00140209 0.00659463 0.00248826 0.00248826 0.00626457 0.00140209
 0.00659463 0.01170335 0.00140209 0.00659463 0.00140209 0.00248826
 0.00248826 0.00261936 0.00140209 0.00140209 0.01170335 0.00140209
 0.00352998 0.00140209 0.00140209 0.00659463 0.00140209 0.00140209
 0.00352998 0.00659463 0.00140209 0.00261936 0.00248826 0.00140209
 0.00140209 0.00248826 0.00352998 0.00352998 0.00248826 0.00248826
 0.00464853 0.00140209 0.00261936 0.00140209 0.00659463 0.00140209
 0.00659463 0.00248826 0.01170335 0.00659463 0.00140209 0.00140209
 0.00464853 0.00464853 0.00261936 0.00140209 0.00248826 0.00248826
 0.00248826 0.00140209 0.00261936 0.01170335 0.00248826 0.0

D= [0.00264952 0.0106296  0.00152086 0.00667055 0.00240286 0.00152086
 0.00152086 0.00667055 0.00264952 0.00679523 0.00269904 0.00269904
 0.00152086 0.00667055 0.00169377 0.00264952 0.00141823 0.00225997
 0.00269904 0.00504229 0.00679523 0.00152086 0.00152086 0.00169377
 0.00169377 0.00401073 0.00269904 0.00152086 0.0079665  0.00095441
 0.00141823 0.00667055 0.00269904 0.00269904 0.00679523 0.00141823
 0.00448898 0.0079665  0.00152086 0.00448898 0.00141823 0.00401073
 0.00269904 0.00422204 0.00225997 0.00141823 0.01269471 0.00152086
 0.00357061 0.00141823 0.00152086 0.00667055 0.00152086 0.00225997
 0.00357061 0.00667055 0.00225997 0.00264952 0.00251691 0.00141823
 0.00152086 0.00269904 0.00240286 0.00568982 0.00269904 0.00169377
 0.00316426 0.00152086 0.00422204 0.00152086 0.00448898 0.00152086
 0.00448898 0.00251691 0.0079665  0.00667055 0.00095441 0.00095441
 0.00470204 0.00504229 0.00264952 0.00152086 0.00269904 0.00169377
 0.00269904 0.00152086 0.00264952 0.0079665  0.00269904 0.0

D= [0.00194028 0.01134815 0.00151025 0.00488494 0.00256529 0.00111375
 0.00151025 0.00662403 0.00263104 0.00497624 0.00288149 0.00268022
 0.00111375 0.0096568  0.00180826 0.00263104 0.00140834 0.00224421
 0.00268022 0.0072996  0.00497624 0.00111375 0.00151025 0.00168196
 0.00180826 0.00398276 0.00288149 0.00220171 0.00850503 0.00094775
 0.00140834 0.00488494 0.00197654 0.00268022 0.00725458 0.00103859
 0.00479243 0.00791094 0.00151025 0.00479243 0.00103859 0.00398276
 0.00390733 0.00309186 0.00224421 0.00103859 0.01355286 0.00151025
 0.00354571 0.00103859 0.00151025 0.00712147 0.00151025 0.00224421
 0.00354571 0.00662403 0.00224421 0.00383564 0.00249936 0.00103859
 0.00151025 0.00197654 0.00347857 0.00416673 0.00390733 0.00245203
 0.0031422  0.00111375 0.00309186 0.00151025 0.00445768 0.00111375
 0.00479243 0.00364367 0.00850503 0.00488494 0.00138167 0.00094775
 0.00466925 0.00369254 0.00194028 0.00111375 0.00390733 0.00124037
 0.00268022 0.00111375 0.00263104 0.00850503 0.00197654 0.0

D= [0.00229314 0.0098348  0.00178491 0.0042335  0.0022232  0.00131629
 0.00130885 0.00782869 0.00228018 0.00431263 0.00340552 0.00316764
 0.00096522 0.008369   0.00156712 0.00228018 0.00122053 0.00194493
 0.00316764 0.00862712 0.00588122 0.00096522 0.00178491 0.00145766
 0.00213712 0.00345163 0.00340552 0.0019081  0.01005176 0.00082136
 0.00122053 0.0042335  0.00171296 0.00232279 0.0085739  0.00090009
 0.00415333 0.00685597 0.00130885 0.00566399 0.00090009 0.00345163
 0.00461792 0.00267954 0.00194493 0.00090009 0.01601759 0.00130885
 0.00307287 0.00090009 0.00178491 0.00617178 0.00178491 0.00194493
 0.00419054 0.00574068 0.00194493 0.00332414 0.00216605 0.00090009
 0.00178491 0.00171296 0.00301468 0.00361107 0.00461792 0.00289795
 0.00371364 0.00096522 0.00365415 0.00130885 0.00526835 0.00096522
 0.00566399 0.00315777 0.01005176 0.0042335  0.00119742 0.00082136
 0.00404658 0.00436407 0.00168153 0.00096522 0.00461792 0.00107496
 0.00316764 0.00131629 0.00228018 0.01005176 0.002336   0.0

  0.5273375 ]


In [12]:
np.sum(prediction10!=np.array(testLabelArr))

16