In [1]:
import bayes

In [2]:
listOPosts,listClasses = bayes.loadDataSet()
myVocabList = bayes.createVocabList(listOPosts)
myVocabList

['maybe',
 'my',
 'mr',
 'love',
 'food',
 'I',
 'so',
 'help',
 'is',
 'licks',
 'problems',
 'him',
 'ate',
 'cute',
 'to',
 'please',
 'stupid',
 'park',
 'flea',
 'dalmation',
 'stop',
 'garbage',
 'dog',
 'posting',
 'quit',
 'take',
 'worthless',
 'how',
 'buying',
 'not',
 'has',
 'steak']

In [3]:
bayes.setOfWords2Vec(myVocabList, listOPosts[0])

[0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0]

In [4]:
bayes.setOfWords2Vec(myVocabList, listOPosts[3])

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0]

In [59]:
import numpy as np
def trainNB0(trainMatrix,trainCategory):
    matrix = np.array(trainMatrix)
    category = np.array(trainCategory)
    p0Num = matrix[trainCategory==0].sum(axis=0)
    p0Denom = p0Num.sum()
    print (p0Num)
    print (p0Denom)
    p0 = matrix[category==0].sum(axis=0) / category[category==0].shape[0]
    #p0 = p0Num / p0Denom
    p1 = matrix[category==1].sum(axis=0) / category[category==1].shape[0]
    pAbusive = category[category==1].shape[0] / category.shape[0]
    return p0, p1, pAbusive

In [60]:
listOPosts,listClasses = bayes.loadDataSet()
myVocabList = bayes.createVocabList(listOPosts)
trainMat=[]
for postinDoc in listOPosts:
    trainMat.append(bayes.setOfWords2Vec(myVocabList, postinDoc))
p0V,p1V,pAb=trainNB0(trainMat,listClasses)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
0


In [61]:
pAb

0.5

In [62]:
p0V

array([0.        , 1.        , 0.33333333, 0.33333333, 0.        ,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.66666667, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.        , 0.        , 0.33333333, 0.33333333,
       0.33333333, 0.        , 0.33333333, 0.        , 0.        ,
       0.        , 0.        , 0.33333333, 0.        , 0.        ,
       0.33333333, 0.33333333])

In [28]:
p1V

array([0.33333333, 0.        , 0.        , 0.        , 0.33333333,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.33333333, 0.        , 0.        , 0.33333333,
       0.        , 1.        , 0.33333333, 0.        , 0.        ,
       0.33333333, 0.33333333, 0.66666667, 0.33333333, 0.33333333,
       0.33333333, 0.66666667, 0.        , 0.33333333, 0.33333333,
       0.        , 0.        ])

In [32]:
def trainNB1(trainMatrix,trainCategory):
    numTrainDocs = len(trainMatrix)
    numWords = len(trainMatrix[0])
    pAbusive = sum(trainCategory)/float(numTrainDocs)
    p0Num = np.zeros(numWords); p1Num = np.zeros(numWords)
    p0Denom = 0.0; p1Denom = 0.0
    for i in range(numTrainDocs):
        if trainCategory[i] == 1:
            p1Num += trainMatrix[i]
            p1Denom += sum(trainMatrix[i])
        else:
            p0Num += trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = p1Num/p1Denom #change to log()
    p0Vect = p0Num/p0Denom #change to log()
    return p0Vect,p1Vect,pAbusive

In [33]:
listOPosts,listClasses = bayes.loadDataSet()
myVocabList = bayes.createVocabList(listOPosts)
trainMat=[]
for postinDoc in listOPosts:
    trainMat.append(bayes.setOfWords2Vec(myVocabList, postinDoc))
p0V,p1V,pAb=trainNB1(trainMat,listClasses)

In [34]:
pAb

0.5

In [35]:
p0V

array([0.        , 0.125     , 0.04166667, 0.04166667, 0.        ,
       0.04166667, 0.04166667, 0.04166667, 0.04166667, 0.04166667,
       0.04166667, 0.08333333, 0.04166667, 0.04166667, 0.04166667,
       0.04166667, 0.        , 0.        , 0.04166667, 0.04166667,
       0.04166667, 0.        , 0.04166667, 0.        , 0.        ,
       0.        , 0.        , 0.04166667, 0.        , 0.        ,
       0.04166667, 0.04166667])