In [1]:
import numpy as np
from numpy import linalg as la
import svdRec

In [2]:
from numpy import *
U,Sigma,VT=np.linalg.svd([[1, 1],[7, 7]])

In [3]:
U

array([[-0.14142136, -0.98994949],
       [-0.98994949,  0.14142136]])

In [4]:
Sigma

array([1.00000000e+01, 2.82797782e-16])

In [5]:
VT

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [6]:
Data=svdRec.loadExData()
U,Sigma,VT=linalg.svd(Data)
Sigma

array([9.72140007e+00, 5.29397912e+00, 6.84226362e-01, 4.11502614e-16,
       1.36030206e-16])

In [7]:
Sig3=mat([[Sigma[0], 0, 0],[0, Sigma[1], 0], [0, 0, Sigma[2]]])
U[:,:3]*Sig3*VT[:3,:]

matrix([[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          7.75989921e-16,  7.71587483e-16],
        [ 2.00000000e+00,  2.00000000e+00,  2.00000000e+00,
          3.00514919e-16,  2.77832253e-16],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          2.18975112e-16,  2.07633779e-16],
        [ 5.00000000e+00,  5.00000000e+00,  5.00000000e+00,
          3.00675663e-17, -1.28697294e-17],
        [ 1.00000000e+00,  1.00000000e+00, -5.48397422e-16,
          2.00000000e+00,  2.00000000e+00],
        [ 3.21319929e-16,  4.43562065e-16, -3.48967188e-16,
          3.00000000e+00,  3.00000000e+00],
        [ 9.71445147e-17,  1.45716772e-16, -1.52655666e-16,
          1.00000000e+00,  1.00000000e+00]])

In [8]:
myMat=np.array(svdRec.loadExData())
svdRec.ecludSim(myMat[:,0],myMat[:,4])  # 三种距离的计算结果都和书上不一样，难道是用的数据不同？

0.13367660240019172

In [9]:
svdRec.ecludSim(myMat[:,0],myMat[:,0])

1.0

In [10]:
svdRec.cosSim(myMat[:,0],myMat[:,4])

0.5472455591261534

In [11]:
svdRec.cosSim(myMat[:,0],myMat[:,0])

0.9999999999999999

In [12]:
svdRec.pearsSim(myMat[:,0],myMat[:,4])

0.23768619407595815

In [13]:
svdRec.pearsSim(myMat[:,0],myMat[:,0])

1.0

In [14]:
myMat=np.array(svdRec.loadExData_2())
myMat[0,1]=myMat[0,0]=myMat[1,0]=myMat[2,0]=4
myMat[3,3]=2
myMat

array([[4, 4, 0, 2, 2],
       [4, 0, 0, 3, 3],
       [4, 0, 0, 1, 1],
       [1, 1, 1, 2, 0],
       [2, 2, 2, 0, 0],
       [1, 1, 1, 0, 0],
       [5, 5, 5, 0, 0]])

In [15]:
svdRec.recommend(myMat, 2)  # 跟书上结果不一样，不知道哪里搞错了

[(2, 2.5), (1, 2.0243290220056256)]

In [16]:
svdRec.recommend(myMat, 2, simMeas=svdRec.ecludSim)

[(2, 3.0), (1, 2.8266504712098603)]

In [17]:
svdRec.recommend(myMat, 2, simMeas=svdRec.pearsSim)

[(2, 2.5), (1, 2.0)]

In [18]:
from numpy import linalg as la
myMat = np.array(svdRec.loadExData2())
U,Sigma,VT=la.svd(myMat)   # 从文件夹里找到的函数
Sigma   # 跟书上不一样？

array([15.77075346, 11.40670395, 11.03044558,  4.84639758,  3.09292055,
        2.58097379,  1.00413543,  0.72817072,  0.43800353,  0.22082113,
        0.07367823])

In [19]:
Sig2=Sigma**2
sum(Sig2)

541.9999999999995

In [20]:
sum(Sig2)*0.9

487.7999999999996

In [21]:
sum(Sig2[:2])

378.8295595113579

In [22]:
sum(Sig2[:3])

500.5002891275793

In [23]:
svdRec.recommend(myMat, 1, estMethod=svdRec.svdEst)

the 0 and 3 similarity is: 0.498297
the 0 and 5 similarity is: 0.498702
the 0 and 10 similarity is: 0.540399
the 1 and 3 similarity is: 0.497432
the 1 and 5 similarity is: 0.497414
the 1 and 10 similarity is: 0.539074
the 2 and 3 similarity is: 0.497835
the 2 and 5 similarity is: 0.497894
the 2 and 10 similarity is: 0.539558
the 4 and 3 similarity is: 0.495847
the 4 and 5 similarity is: 0.500120
the 4 and 10 similarity is: 0.501394
the 6 and 3 similarity is: 0.750797
the 6 and 5 similarity is: 0.636231
the 6 and 10 similarity is: 0.623186
the 7 and 3 similarity is: 0.500010
the 7 and 5 similarity is: 0.502570
the 7 and 10 similarity is: 0.544420
the 8 and 3 similarity is: 0.500932
the 8 and 5 similarity is: 0.502238
the 8 and 10 similarity is: 0.544006
the 9 and 3 similarity is: 0.530070
the 9 and 5 similarity is: 0.518088
the 9 and 10 similarity is: 0.517555


[(4, 3.334001055799355),
 (9, 3.330895617349481),
 (7, 3.3248674803258678),
 (8, 3.324616235400013),
 (0, 3.32438068443843),
 (2, 3.3243000943728127),
 (1, 3.324276526003641),
 (6, 3.3164990076214846)]

In [24]:
svdRec.recommend(myMat, 1, estMethod=svdRec.svdEst,simMeas=svdRec.pearsSim)

the 0 and 3 similarity is: 0.260009
the 0 and 5 similarity is: 0.267319
the 0 and 10 similarity is: 0.304773
the 1 and 3 similarity is: 0.259671
the 1 and 5 similarity is: 0.266348
the 1 and 10 similarity is: 0.303700
the 2 and 3 similarity is: 0.259959
the 2 and 5 similarity is: 0.266751
the 2 and 10 similarity is: 0.304128
the 4 and 3 similarity is: 0.269958
the 4 and 5 similarity is: 0.282481
the 4 and 10 similarity is: 0.259976
the 6 and 3 similarity is: 0.693294
the 6 and 5 similarity is: 0.543264
the 6 and 10 similarity is: 0.517233
the 7 and 3 similarity is: 0.237709
the 7 and 5 similarity is: 0.248966
the 7 and 10 similarity is: 0.286199
the 8 and 3 similarity is: 0.261446
the 8 and 5 similarity is: 0.270112
the 8 and 10 similarity is: 0.307803
the 9 and 3 similarity is: 0.299239
the 9 and 5 similarity is: 0.288007
the 9 and 10 similarity is: 0.261465


[(4, 3.3477049430350485),
 (9, 3.3393469031787215),
 (7, 3.3221301186012315),
 (8, 3.321806644564644),
 (0, 3.3212579735685965),
 (2, 3.3210621579633552),
 (1, 3.321009939503826),
 (6, 3.309765500739301)]

In [25]:
svdRec.imgCompress(2)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
****original matrix******
0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,